"""add admin notes to user reports

Revision ID: 22ef7a63a142
Revises: 8e0aca3529c4
Create Date: 2026-10-03 00:24:21.839801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ef7a63a142'
down_revision = '8e0aca3529c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reports', schema=None) as batch_op:
        batch_op.drop_column('admin_notes')

    # ### end Alembic commands ###
