"""Add language fields for translation feature

Revision ID: 5d50ce8b8647
Revises: 36e212eca150
Create Date: 2026-08-18 23:28:55.878957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d50ce8b8647'
down_revision = '36e212eca150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_language', sa.String(length=10), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_language')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('original_language')

    # ### end Alembic commands ###
