"""Add spoken languages to user profile

Revision ID: 8b731e32836c
Revises: 8b59355d4e87
Create Date: 2026-09-25 13:56:32.015981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b731e32836c'
down_revision = '8b59355d4e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('languages_spoken', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('languages_spoken')

    # ### end Alembic commands ###
