"""Add age and country to user profile

Revision ID: 968c3fdfc970
Revises: 0e699b75ff82
Create Date: 2026-09-20 20:48:39.709110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968c3fdfc970'
down_revision = '0e699b75ff82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
