"""add image support to messages

Revision ID: e26faf40ee8a
Revises: 22ef7a63a142
Create Date: 2026-10-04 00:51:23.502443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26faf40ee8a'
down_revision = '22ef7a63a142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('media_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('media_url')
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###
